//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirdProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B腳環
    {
        public int Id { get; set; }
        public int VerificationId { get; set; }
        public string Bird左右腳 { get; set; }
        public string Bird腳環類型 { get; set; }
        public string Bird腳環顏色 { get; set; }
        public string Bird腳環號碼 { get; set; }
    
        public virtual B鳥 B鳥 { get; set; }
    }
}
